CREATE TABLE IF NOT EXISTS roles (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(160) NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS setores (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS modulos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    codigo VARCHAR(50) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS tipos_recursos (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categorias_prestador (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    slug VARCHAR(50) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tipos_ata (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS setores_modulos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    setor_id INT UNSIGNED NOT NULL,
    modulo_id INT UNSIGNED NOT NULL,
    pode_visualizar BOOLEAN NOT NULL DEFAULT TRUE,
    pode_criar BOOLEAN NOT NULL DEFAULT FALSE,
    pode_editar BOOLEAN NOT NULL DEFAULT FALSE,
    pode_excluir BOOLEAN NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_setores_modulos_modulo FOREIGN KEY (modulo_id) REFERENCES modulos(id) ON UPDATE CASCADE ON DELETE CASCADE
); 

CREATE TABLE IF NOT EXISTS usuarios (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(100) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role_id INT UNSIGNED NOT NULL,
    setor_id INT UNSIGNED,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP

    CONSTRAINT fk_usuarios_role FOREIGN KEY (role_id) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_usuarios_setor FOREIGN KEY (setor_id) REFERENCES setores(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS recursos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipo_recursos_id INT UNSIGNED NOT NULL,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'disponivel',
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_recursos_tipo_recurso FOREIGN KEY (tipo_recursos_id) REFERENCES tipos_recursos(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS prestadores (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(160) NOT NULL,
    categoria_id INT UNSIGNED NOT NULL,
    situacao VARCHAR(30) NOT NULL DEFAULT 'ativo',
    email_notificacao VARCHAR(255) NULL,
    receber_avisos BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_prestadores_categoria FOREIGN KEY (categoria_id) REFERENCES categorias_prestador (id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS arquivos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome_original VARCHAR(255) NOT NULL,
    nome_armazenado VARCHAR(255) NOT NULL,
    caminho_relativo VARCHAR(500) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    tamanho_bytes BIGINT UNSIGNED NOT NULL,
    hash_sha256 CHAR(64) UNSIGNED NULL,
    enviado_por_id INT UNSIGNED NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_arquivos_usuario FOREIGN KEY (enviado_por_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS reservas (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    recursos_id INT UNSIGNED NOT NULL,
    usuario_id INT UNSIGNED NULL,
    setor_id INT UNSIGNED NULL,
    responsavel VARCHAR(100) NULL,
    motivo VARCHAR(150) NULL,
    data_reserva DATE NOT NULL,
    data_volta DATE NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NULL,
    observacao TEXT NULL,
    viagem BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'reservado',
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_reservas_recurso FOREIGN KEY (recurso_id) REFERENCES recursos(id) ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_reservas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_reservas_setor FOREIGN KEY (setor_id) REFERENCES setores(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS agenda_compromissos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(160) NOT NULL,
    data DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NULL,
    responsavel VARCHAR(120) NULL,
    local VARCHAR(140) NULL,
    descricao TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'agendado',
    criado_por_id INT UNSIGNED NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_agenda_criado_por FOREIGN KEY (criado_por_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS documentos_prestador (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    prestador_id INT UNSIGNED NOT NULL,
    nome VARCHAR(255) NOT NULL,
    data_vencimento DATE NULL,
    data_notificacao DATE NULL,
    sem_validade BOOLEAN NOT NULL DEFAULT FALSE,
    nao_indicado BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    status_manual BOOLEAN NOT NULL DEFAULT FALSE,
    observacao TEXT NULL,
    arquivo_id INT UNSIGNED NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_documentos_prestador FOREIGN KEY (prestador_id) REFERENCES prestadores(id) ON UPDATE CASCADE, ON DELETE CASCADE,

    CONSTRAINT fk_documentos_prestador FOREIGN KEY (arquivo_id) REFERENCES arquivos(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS descredenciamentos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    prestador_id INT NOT NULL AUTO_INCREMENT,
    motivo TEXT NOT NULL,
    arquivo_id INT UNSIGNED NULL,
    registrado_por_id INT UNSIGNED NULL,
    descredenciado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_descredenciamentos_prestador FOREIGN KEY (prestador_id) REFERENCES prestadores(id) ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT fk_descredenciamentos_arquivos FOREIGN KEY (arquivos_id) REFERENCES arquivos(id) ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_descredenciamentos_usuarios FOREIGN KEY (registrado_por_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS atas_reunião (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    numero_ata VARCHAR(50) NOT NULL,
    data_reuniao DATE NOT NULL,
    tipo_ata_id INT UNSIGNED NOT NULL,
    pauta TEXT NOT NULL,
    participantes TEXT NOT NULL,
    arquivo_id INT UNSIGNED NULL,
    criado_por_id INT UNSIGNED NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_atas_arquivos FOREIGN KEY (tipos_ata_id) REFERENCES tipos_ata(id) ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_atas_arquivos FOREIGN KEY (arquivo_id) REFERENCES arquivos(id) ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_atas_criado_por FOREIGN KEY (criado_por_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS avisos_email_enviados (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    documento_id INT UNSIGNED NOT NULL,
    prestador_id INT UNSIGNED NOT NULL,
    email_destinatario VARCHAR(255) NOT NULL,
    chave VARCHAR(100) NOT NULL,
    enviado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_avisos_documento FOREIGN KEY (documento_id) REFERENCES documentos_prestador(id) ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT fk_avisos_prestador FOREIGN KEY (prestador_id) REFERENCES prestadores(id) ON UPDATE CASCADE ON DELETE CASCADE
);